name: release
on:
    push:
        tags:
            - "v*"
jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout
            - run: git fetch --prune --unshallow
            - name: Setup Go
              uses: actions/setup-go
              with:
                go-version: 1.16
            - name: Import GPG Key
              id: import_gpg
              uses: hashicorp/ghaction-import-gpg
              env:
                GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                PASSPHRASE: ${{ secrets.PASSPHRASE }}
            - name: GoReleaser
              uses: goreleaser/goreleaser-action
              with:
                version: latest
                args: release --rm-dist
              env:
                GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
